/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/rabbis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rabbis */
        get: operations["list_rabbis_api_rabbis_get"];
        put?: never;
        /** Create Rabbi */
        post: operations["create_rabbi_api_rabbis_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rabbis/{rabbi_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Rabbi */
        put: operations["update_rabbi_api_rabbis__rabbi_id__put"];
        post?: never;
        /** Delete Rabbi */
        delete: operations["delete_rabbi_api_rabbis__rabbi_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Series */
        get: operations["list_series_api_series_get"];
        put?: never;
        /** Create Series */
        post: operations["create_series_api_series_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/series/{series_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Series */
        get: operations["get_series_api_series__series_id__get"];
        /** Update Series */
        put: operations["update_series_api_series__series_id__put"];
        post?: never;
        /** Delete Series */
        delete: operations["delete_series_api_series__series_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/series/{series_id}/lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Series Lessons */
        get: operations["list_series_lessons_api_series__series_id__lessons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/series/{series_id}/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview Reset Series */
        get: operations["preview_reset_series_api_series__series_id__reset_get"];
        put?: never;
        /** Reset Series */
        post: operations["reset_series_api_series__series_id__reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lab/lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Lab Lessons
         * @description AL §2's selection axes: rabbi/series/lesson_type, or an explicit id list —
         *     applied live against public.lessons (AL §1.1), no seeding step.
         */
        get: operations["list_lab_lessons_api_lab_lessons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lab/lessons/{lesson_id}/ensure-cached": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ensure Cached
         * @description Synchronous — a single file download is short enough that blocking on it
         *     isn't worth run_job.py's tracking machinery (AL §4.6).
         */
        post: operations["ensure_cached_api_lab_lessons__lesson_id__ensure_cached_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lab/lessons/{lesson_id}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Lesson Jobs */
        get: operations["list_lesson_jobs_api_lab_lessons__lesson_id__jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lab/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Job */
        post: operations["create_job_api_lab_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lab/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_lab_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CacheStatus
         * @description Not the same enumeration as db.status.LessonStatus (admin-lab-plan.md §0.2) —
         *     this is about local file presence, not catalogue pipeline progress.
         * @enum {string}
         */
        CacheStatus: "not_stored" | "stored" | "cached";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** JobCreate */
        JobCreate: {
            /** Lesson Id */
            lesson_id: number;
            /** Job Type */
            job_type: string;
            /** Params */
            params: {
                [key: string]: unknown;
            };
        };
        /**
         * LabJobRead
         * @description Maps 1:1 onto LabJobRow's columns, so from_attributes is enough here
         *     (contrast schemas/catalogue.py's Read models, which need joined/computed
         *     fields).
         */
        LabJobRead: {
            /** Id */
            id: number;
            /** Lesson Id */
            lesson_id: number;
            /** Job Type */
            job_type: string;
            /** Job Version */
            job_version: string;
            /** Job Description */
            job_description: string;
            /** Job Version Notes */
            job_version_notes: string;
            /** Status */
            status: string;
            /** Pid */
            pid: number | null;
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /** Model Id */
            model_id: string;
            /** Result Json */
            result_json: {
                [key: string]: unknown;
            } | null;
            /** Log */
            log: string | null;
            /** Error */
            error: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at: string | null;
            /** Git Sha */
            git_sha: string;
            /** Git Dirty */
            git_dirty: boolean;
        };
        /**
         * LabLessonRead
         * @description Built explicitly (not from_attributes) — series_name_en/rabbi_name_en are
         *     joined, and cache_status is computed against local_cache_dir, neither a Lesson
         *     attribute.
         */
        LabLessonRead: {
            /** Id */
            id: number;
            /** Series Id */
            series_id: number;
            /** Series Name En */
            series_name_en: string;
            /** Rabbi Name En */
            rabbi_name_en: string;
            /** Title He */
            title_he: string;
            /** Title En */
            title_en: string | null;
            /** Lesson Type */
            lesson_type: string;
            /** Recorded At */
            recorded_at: string | null;
            cache_status: components["schemas"]["CacheStatus"];
        };
        /**
         * LessonRead
         * @description Built explicitly (not from_attributes) — status is computed by
         *     db.status.lesson_status(), not a Lesson attribute.
         */
        LessonRead: {
            /** Id */
            id: number;
            /** External Id */
            external_id: string;
            /** Url */
            url: string;
            /** Title He */
            title_he: string;
            /** Title En */
            title_en: string | null;
            /** Lesson Type */
            lesson_type: string;
            /** Published At */
            published_at: string | null;
            /** Recorded At */
            recorded_at: string | null;
            /**
             * Discovered At
             * Format: date-time
             */
            discovered_at: string;
            status: components["schemas"]["LessonStatus"];
        };
        /**
         * LessonStatus
         * @enum {string}
         */
        LessonStatus: "discovered" | "downloaded" | "stored";
        /**
         * RabbiRead
         * @description Built explicitly (not from_attributes) — series_count is a query-side
         *     aggregate, not a Rabbi attribute.
         */
        RabbiRead: {
            /** Id */
            id: number;
            /** Name He */
            name_he: string;
            /** Name En */
            name_en: string;
            /** Slug */
            slug: string;
            /** Series Count */
            series_count: number;
        };
        /** RabbiWrite */
        RabbiWrite: {
            /** Name He */
            name_he: string;
            /** Name En */
            name_en: string;
            /** Slug */
            slug: string;
        };
        /** ResetPreview */
        ResetPreview: {
            /** Lesson Count */
            lesson_count: number;
            /** Warning */
            warning: string;
        };
        /** ResetResult */
        ResetResult: {
            /** Deleted Count */
            deleted_count: number;
        };
        /**
         * SeriesRead
         * @description Built explicitly, same reasoning as RabbiRead — rabbi_name_en/lesson_count
         *     are joined/aggregated, not Series attributes.
         */
        SeriesRead: {
            /** Id */
            id: number;
            /** Rabbi Id */
            rabbi_id: number;
            /** Rabbi Name En */
            rabbi_name_en: string;
            /** Name He */
            name_he: string;
            /** Name En */
            name_en: string;
            /** Slug */
            slug: string;
            /** Lesson Type */
            lesson_type: string;
            /** Adapter Key */
            adapter_key: string;
            /** Description He */
            description_he: string | null;
            /** Description En */
            description_en: string | null;
            /** Lesson Count */
            lesson_count: number;
        };
        /** SeriesWrite */
        SeriesWrite: {
            /** Rabbi Id */
            rabbi_id: number;
            /** Name He */
            name_he: string;
            /** Name En */
            name_en: string;
            /** Slug */
            slug: string;
            /** Lesson Type */
            lesson_type: string;
            /** Adapter Key */
            adapter_key: string;
            /** Description He */
            description_he?: string | null;
            /** Description En */
            description_en?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_rabbis_api_rabbis_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RabbiRead"][];
                };
            };
        };
    };
    create_rabbi_api_rabbis_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RabbiWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RabbiRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_rabbi_api_rabbis__rabbi_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rabbi_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RabbiWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RabbiRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_rabbi_api_rabbis__rabbi_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rabbi_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_series_api_series_get: {
        parameters: {
            query?: {
                rabbi_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_series_api_series_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeriesWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_series_api_series__series_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_series_api_series__series_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeriesWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_series_api_series__series_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_series_lessons_api_series__series_id__lessons_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_reset_series_api_series__series_id__reset_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_series_api_series__series_id__reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_lab_lessons_api_lab_lessons_get: {
        parameters: {
            query?: {
                rabbi_id?: number | null;
                series_id?: number | null;
                lesson_type?: string | null;
                lesson_ids?: number[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabLessonRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ensure_cached_api_lab_lessons__lesson_id__ensure_cached_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabLessonRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_lesson_jobs_api_lab_lessons__lesson_id__jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabJobRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_api_lab_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabJobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_lab_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabJobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
