"""Add lesson_downloads table

Revision ID: 04d2172a31ec
Revises: 4cd7e43ff92e
Create Date: 2026-08-10 20:54:12.796860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04d2172a31ec'
down_revision: Union[str, Sequence[str], None] = '4cd7e43ff92e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_downloads',
    sa.Column('lesson_id', sa.BigInteger(), nullable=False),
    sa.Column('local_path', sa.Text(), nullable=False),
    sa.Column('bytes', sa.BigInteger(), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_lesson_downloads_lesson_id_lessons')),
    sa.PrimaryKeyConstraint('lesson_id', name=op.f('pk_lesson_downloads'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lesson_downloads')
    # ### end Alembic commands ###
