"""Add rabbis, series, lessons, audio_files, lesson_duplicates

Revision ID: 4cd7e43ff92e
Revises: 
Create Date: 2026-08-09 22:35:13.780776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cd7e43ff92e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rabbis',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name_he', sa.Text(), nullable=False),
    sa.Column('name_en', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rabbis')),
    sa.UniqueConstraint('slug', name=op.f('uq_rabbis_slug'))
    )
    op.create_table('series',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('rabbi_id', sa.BigInteger(), nullable=False),
    sa.Column('name_he', sa.Text(), nullable=False),
    sa.Column('name_en', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('lesson_type', sa.Text(), nullable=False),
    sa.Column('adapter_key', sa.Text(), nullable=False),
    sa.Column('description_he', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rabbi_id'], ['rabbis.id'], name=op.f('fk_series_rabbi_id_rabbis')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_series')),
    sa.UniqueConstraint('slug', name=op.f('uq_series_slug'))
    )
    op.create_table('lessons',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('series_id', sa.BigInteger(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title_he', sa.Text(), nullable=False),
    sa.Column('title_en', sa.Text(), nullable=True),
    sa.Column('description_he', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('lesson_type', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name=op.f('fk_lessons_series_id_series')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lessons')),
    sa.UniqueConstraint('series_id', 'external_id', name=op.f('uq_lessons_series_id'))
    )
    op.create_table('audio_files',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('lesson_id', sa.BigInteger(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('format', sa.Text(), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=False),
    sa.Column('bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_audio_files_lesson_id_lessons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audio_files')),
    sa.UniqueConstraint('lesson_id', name=op.f('uq_audio_files_lesson_id')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_audio_files_storage_key'))
    )
    op.create_index(op.f('ix_audio_files_content_hash'), 'audio_files', ['content_hash'], unique=False)
    op.create_table('lesson_duplicates',
    sa.Column('lesson_id', sa.BigInteger(), nullable=False),
    sa.Column('duplicate_of_id', sa.BigInteger(), nullable=False),
    sa.Column('method', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['lessons.id'], name=op.f('fk_lesson_duplicates_duplicate_of_id_lessons')),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_lesson_duplicates_lesson_id_lessons')),
    sa.PrimaryKeyConstraint('lesson_id', name=op.f('pk_lesson_duplicates'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lesson_duplicates')
    op.drop_index(op.f('ix_audio_files_content_hash'), table_name='audio_files')
    op.drop_table('audio_files')
    op.drop_table('lessons')
    op.drop_table('series')
    op.drop_table('rabbis')
    # ### end Alembic commands ###
