"""Add lab schema and lab_jobs table

Revision ID: a12032085f36
Revises: 04d2172a31ec
Create Date: 2026-08-14 16:34:52.545129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a12032085f36'
down_revision: Union[str, Sequence[str], None] = '04d2172a31ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS lab")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('lesson_id', sa.BigInteger(), nullable=False),
    sa.Column('job_type', sa.Text(), nullable=False),
    sa.Column('job_version', sa.Text(), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('job_version_notes', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_id', sa.Text(), nullable=False),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('log', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('git_sha', sa.Text(), nullable=False),
    sa.Column('git_dirty', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_lab_jobs_lesson_id_lessons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lab_jobs')),
    schema='lab'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lab_jobs', schema='lab')
    # ### end Alembic commands ###
    # `lab` schema itself is left in place (admin-lab.md §5.4 — a general-purpose
    # scratch namespace meant to outlive any single lab, later migrations may add
    # tables to it independently of this one).
