"""Survey a source before deciding anything about it.
documents/plans/adding-series-plan.md §3.

    uv run python -m data_pipelines.pipelines.discover.prediscover <source-slug>

Reads a source, writes `documents/pipelines/sources/<source>.proposal.yaml`, and touches
nothing else — not the database, not the catalogue. Which of מכון מאיר's 170 playlists
are worth having is a judgement call; enumerating them, counting them and guessing at
the speaker is mechanical, and that split is the entire argument for the step existing.

**The output is a draft of a delta file, not a replacement for the catalogue.** You read
it, delete the 80% you don't want, fix the transliterations — which are generated by a
letter-for-letter table and will be wrong for most names — and seed what's left. A
re-run rewrites the proposal and can never clobber your edits, because your edits live
in `seed_data/additions/` and this writes somewhere else entirely.

Run rarely: when a source is added or revisited. Not part of the nightly discover run.
It lists every playlist on the channel, which for הר עציון is 561 yt-dlp invocations.
"""

import argparse
import re
from collections import Counter
from dataclasses import dataclass, field
from pathlib import Path

from rich.console import Console
from sqlalchemy import create_engine, select
from sqlalchemy.orm import Session

from data_pipelines.adapters import names, youtube_api
from data_pipelines.adapters.youtube import list_playlist_flat, uploads_playlist_id
from data_pipelines.config import get_settings
from data_pipelines.db import Source
from data_pipelines.progress import label, make_progress

DEFAULT_OUT_DIR = Path("documents/pipelines/sources")

# Below this, a playlist is more likely a stub than a series. Reported, never dropped:
# הר עציון has 165 playlists under it and some of them are real.
SMALL_PLAYLIST = 5

# Both are used as the speaker/series separator, on different channels and sometimes in
# one title: Meir writes `הלכה יומית - אורח חיים - הרב מרדכי ענתבי`, others use `|`.
_PLAYLIST_SEPARATOR_RE = re.compile(r"\s*[|]\s*|\s+[-–]\s+")


@dataclass
class PlaylistSurvey:
    """One playlist, with everything the accept decision needs on one line."""

    id: str
    title: str
    item_count: int
    speaker: str | None
    series_name: str

    @property
    def confident(self) -> bool:
        """A playlist whose title names a rabbi and which holds enough lessons to be a
        series. Only a marker in the output — nothing is filtered on it."""
        return self.speaker is not None and self.item_count >= SMALL_PLAYLIST


@dataclass
class SourceSurvey:
    source_slug: str
    channel_id: str
    playlists: list[PlaylistSurvey] = field(default_factory=list)
    video_count: int = 0
    in_a_playlist: int = 0
    # Video titles' speaker census — the title-routed case, where the series boundary is
    # a name rather than a location.
    title_speakers: Counter[str] = field(default_factory=Counter)

    @property
    def orphans(self) -> int:
        return self.video_count - self.in_a_playlist

    @property
    def unnamed_playlists(self) -> list[PlaylistSurvey]:
        return [p for p in self.playlists if p.speaker is None]

    @property
    def small_playlists(self) -> list[PlaylistSurvey]:
        return [p for p in self.playlists if p.item_count < SMALL_PLAYLIST]

    def substring_collisions(self) -> list[tuple[str, str]]:
        """Census names where one contains the other, **surnames included**.

        The thing this survey exists to catch before a rule is written: `אבוטבול`
        contains `בוטבול`, `לוינשטיין` contains `לוי`, and each pair is two different
        rabbis. Comparing whole names alone finds almost nothing — `אהרן בוטבול` is not
        a substring of `אהרן אבוטבול` — which is why the last word is compared too;
        that is where the trap actually lives.

        Alias resolution matches whole names, so nothing here is silently mismatched.
        This is for the curator, who is about to write a rule and needs to know these
        are two men and not one man spelled twice."""
        found = sorted(self.title_speakers)
        collisions = []
        for shorter in found:
            for longer in found:
                if shorter == longer:
                    continue
                surnames = (shorter.split()[-1], longer.split()[-1])
                if shorter in longer or (
                    surnames[0] != surnames[1] and surnames[0] in surnames[1]
                ):
                    collisions.append((shorter, longer))
        return collisions


def split_playlist_title(title: str) -> tuple[str | None, str]:
    """`(speaker, series_name)` from a playlist title.

    The rabbi is not always in the same place — Meir puts him last, other channels
    first — so the segment that carries an honorific is the speaker and whatever is left
    is the series, rather than either position being assumed."""
    segments = [s for s in _PLAYLIST_SEPARATOR_RE.split(names.normalize(title)) if s]
    for index, segment in enumerate(segments):
        found = names.find_speaker(segment, max_words=3)
        if found is not None:
            rest = segments[:index] + segments[index + 1 :]
            return found[0], " - ".join(rest) or segment
    return None, names.normalize(title)


# Letter-for-letter, and knowingly crude: there is no source for how these names are
# spelled in English (§7.1), so this produces something typeable that a curator corrects
# rather than pretending to know. Every slug it emits is marked as a guess in the output.
_TRANSLITERATION = {
    "א": "a", "ב": "b", "ג": "g", "ד": "d", "ה": "h", "ו": "o", "ז": "z", "ח": "ch",
    "ט": "t", "י": "i", "כ": "k", "ך": "k", "ל": "l", "מ": "m", "ם": "m", "נ": "n",
    "ן": "n", "ס": "s", "ע": "a", "פ": "p", "ף": "p", "צ": "tz", "ץ": "tz", "ק": "k",
    "ר": "r", "ש": "sh", "ת": "t",
}


def suggest_slug(name: str, *, prefix: str = "") -> str:
    latin = "".join(_TRANSLITERATION.get(char, char if char.isascii() else " ") for char in name)
    slug = re.sub(r"[^a-z0-9]+", "-", latin.lower()).strip("-")
    return f"{prefix}{slug}" if slug else f"{prefix}unnamed"


def unique_slugs(values: list[str], *, prefix: str = "") -> dict[str, str]:
    """A slug per value, guaranteed distinct — and that guarantee is the point.

    א and ע both carry no consonant of their own, so `אהרן בוטבול` and `אהרן אבוטבול`
    transliterate identically. Two different rabbis handed one slug do not produce an
    error when seeded: they produce one speaker row with both men's lessons under it,
    which is the exact failure kolel-channels.md §3.2 warns about, arriving through the
    back door. So the second one gets a numeric suffix and, in the output, a marker
    telling the curator to give it a real name."""
    slugs: dict[str, str] = {}
    used: set[str] = set()
    for value in values:
        # A repeated *value* is one thing named twice, not a collision: two playlists
        # reducing to the same series name is routine once the speaker segment is
        # stripped. Renaming the second would map the value to `-2` and leave the
        # unsuffixed slug attached to nothing.
        if value in slugs:
            continue
        base = suggest_slug(value, prefix=prefix)
        slug = base
        suffix = 2
        while slug in used:
            slug = f"{base}-{suffix}"
            suffix += 1
        used.add(slug)
        slugs[value] = slug
    return slugs


def collided(slug: str) -> bool:
    """Whether `unique_slugs` had to disambiguate this one."""
    return bool(re.search(r"-\d+$", slug))


def survey(source: Source, console: Console) -> SourceSurvey:
    if source.platform != "youtube":
        raise ValueError(f"{source.slug} is a {source.platform} source; this surveys YouTube")

    result = SourceSurvey(source_slug=source.slug, channel_id=source.external_id)
    with make_progress() as progress:
        uploads_task = progress.add_task(label(f"Listing {source.slug}"), total=None)
        uploads = list_playlist_flat(uploads_playlist_id(source.external_id))
        progress.remove_task(uploads_task)
        result.video_count = len(uploads)

        for entry in uploads:
            found = names.find_speaker(names.normalize(entry["title"]))
            if found is not None:
                result.title_speakers[found[0]] += 1

        playlists = list(youtube_api.list_channel_playlists(source.external_id))
        members: set[str] = set()
        task = progress.add_task(label("Playlists"), total=len(playlists))
        for playlist in playlists:
            speaker, series_name = split_playlist_title(playlist.title)
            result.playlists.append(
                PlaylistSurvey(
                    id=playlist.id,
                    title=names.normalize(playlist.title),
                    item_count=playlist.item_count,
                    speaker=speaker,
                    series_name=series_name,
                )
            )
            members.update(entry["id"] for entry in list_playlist_flat(playlist.id))
            progress.advance(task)
        progress.remove_task(task)

    upload_ids = {entry["id"] for entry in uploads}
    result.in_a_playlist = len(members & upload_ids)
    console.print(f"[bold]{source.slug}[/]: {result.video_count} videos, "
                  f"{len(result.playlists)} playlists")
    return result


def _yaml_string(value: str) -> str:
    """Quoted only when it has to be. Hebrew needs no quoting; a leading `"` or a colon
    does, and these titles have plenty of both."""
    # The leading-character class is every YAML indicator, flow collections included: a
    # playlist titled `[חדש] ...` emitted unquoted makes the whole proposal file
    # unparseable, which is a strange way to find out about a playlist.
    if value and not re.search(r'^[\s"\'\-&*#|>%@`!?:,\[\]{}~]|: |:$|\s#|\s$', value):
        return value
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_proposal(result: SourceSurvey) -> str:
    """A delta file with the counts and the warnings written in as comments.

    Comments rather than extra fields, because the file's other job is to be seedable
    the moment you have finished deleting from it — `CatalogueSeed` has nowhere to put
    an item count, and inventing somewhere would mean this file could no longer be
    handed straight to `seed_catalogue`."""
    lines = [
        f"# Proposal for source `{result.source_slug}` ({result.channel_id}) —"
        " generated by prediscover.",
        "# A DRAFT of a delta file: delete what you don't want, fix every slug and every",
        "# name_en (all guessed, letter-for-letter), then seed what's left with",
        "#   uv run python -m data_pipelines.catalogue.seed_catalogue --input <this> --delta",
        "# Nothing here has touched the database. Re-running overwrites this file only.",
        "#",
        f"# {result.video_count} videos, {len(result.playlists)} playlists.",
        f"# In no playlist: {result.orphans}"
        f" ({result.orphans / result.video_count:.1%} of the channel)"
        if result.video_count
        else "# In no playlist: n/a (no videos)",
        f"# Playlists whose title yields no speaker: {len(result.unnamed_playlists)}"
        f" of {len(result.playlists)}",
        f"# Playlists with fewer than {SMALL_PLAYLIST} items: {len(result.small_playlists)}",
    ]
    collisions = result.substring_collisions()
    if collisions:
        lines.append(
            f"# Names that contain another name ({len(collisions)}) — different rabbis, not"
            " spellings:"
        )
        lines += [f"#   {shorter}  ⊂  {longer}" for shorter, longer in collisions[:20]]
    lines.append("#")
    lines.append("# Speaker census from video titles (top 30):")
    for name, count in result.title_speakers.most_common(30):
        lines.append(f"#   {count:>5}  {name}  →  {suggest_slug(name, prefix='r-')}")
    lines.append("")

    census_speakers = [name for name, _ in result.title_speakers.most_common(30)]
    playlist_speakers = sorted({p.speaker for p in result.playlists if p.speaker})
    # One mapping for the whole file: the speakers list, the alias rows and every rule's
    # `default_speaker` have to agree, and computing a slug twice is how they stop
    # agreeing.
    speaker_slugs = unique_slugs(
        sorted(set(census_speakers) | set(playlist_speakers)), prefix="r-"
    )
    series_slugs = unique_slugs([p.series_name for p in result.playlists])

    lines.append("speakers:")
    for name, slug in speaker_slugs.items():
        marker = "    # GUESS — SLUG COLLIDED, rename" if collided(slug) else "    # GUESS"
        lines.append(f"- slug: {slug}{marker}")
        lines.append(f"  name_he: {_yaml_string('הרב ' + name)}")
        english = slug.removeprefix("r-").replace("-", " ").title()
        lines.append(f"  name_en: {_yaml_string('Rabbi ' + english)}    # GUESS")
    lines.append("")
    lines.append("# One row per spelling the source actually uses — that is what merges two")
    lines.append("# spellings of one man, and what keeps two men with similar names apart.")
    lines.append("speaker_aliases:")
    for name, slug in speaker_slugs.items():
        lines.append(f"- name_he: {_yaml_string(name)}")
        lines.append(f"  speaker: {slug}")
    lines.append("")

    by_size = sorted(result.playlists, key=lambda p: -p.item_count)
    lines.append("series:")
    seen_series: set[str] = set()
    for playlist in by_size:
        slug = series_slugs[playlist.series_name]
        # Two playlists can reduce to one series name — a rabbi's lessons split across
        # two playlists is one series fed by two rules, and emitting the row twice
        # would make the file invalid for no gain. The rules below still get one entry
        # each, which is the half that has to be per-playlist.
        if slug in seen_series:
            continue
        seen_series.add(slug)
        marker = "" if playlist.confident else "    # LOW CONFIDENCE"
        lines.append(f"# {playlist.item_count} items — {playlist.title}")
        lines.append(f"- slug: {slug}{marker}")
        lines.append(f"  name_he: {_yaml_string(playlist.series_name)}")
        lines.append(f"  name_en: {_yaml_string(slug.replace('-', ' ').title())}    # GUESS")
        if collided(slug):
            lines.append("  # SLUG COLLIDED with another series' — rename before seeding")
        lines.append("  lesson_type: halacha    # GUESS — pick from the catalogue's lesson_types")
    lines.append("")

    lines.append("ingest_rules:")
    for playlist in by_size:
        lines.append(f"# {playlist.item_count} items — {playlist.title}")
        lines.append(f"- source: {result.source_slug}")
        lines.append(f"  series: {series_slugs[playlist.series_name]}")
        lines.append("  kind: youtube_playlist")
        lines.append(f"  config: {{playlist_id: {playlist.id}}}")
        if playlist.speaker:
            lines.append(f"  default_speaker: {speaker_slugs[playlist.speaker]}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source_slug")
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    args = parser.parse_args()

    console = Console()
    engine = create_engine(get_settings().database_url())
    with Session(engine, expire_on_commit=False) as session:
        source = session.scalar(select(Source).where(Source.slug == args.source_slug))
        if source is None:
            # The source row comes first, always: a survey of a channel the catalogue
            # has never heard of has nowhere to file its answer.
            raise SystemExit(
                f"no source {args.source_slug!r} — seed the `sources` row first, then survey it"
            )
        result = survey(source, console)

    args.out_dir.mkdir(parents=True, exist_ok=True)
    out_path = args.out_dir / f"{args.source_slug}.proposal.yaml"
    out_path.write_text(render_proposal(result), encoding="utf-8")

    console.print(f"[bold]{result.orphans}[/] videos in no playlist "
                  f"({result.orphans / result.video_count:.1%})" if result.video_count else "")
    console.print(f"[bold]{len(result.unnamed_playlists)}[/] playlists name no speaker; "
                  f"[bold]{len(result.small_playlists)}[/] have fewer than {SMALL_PLAYLIST} items")
    console.print(f"Wrote {out_path} — review it, then seed with --delta")


if __name__ == "__main__":
    main()
